import Link from "next/link";

import { EditorialText, ImageReveal, MediaFrame, MetaTable } from "@/components/zentura/blocks";
import { renewablyImages } from "@/content/site";



function Study() { return <article className="pb-24"><Link href="/work" className="mb-8 inline-block font-mono text-label uppercase text-ink underline underline-offset-3 min-[720px]:hidden">Back to Work</Link><p className="mb-4 font-mono text-label text-ink-muted">INDEX / RENEWABLY UK</p><ImageReveal immediate><MediaFrame {...renewablyImages.wide} sizes="(min-width: 1180px) 1026px, (min-width: 720px) calc(100vw - 345px), calc(100vw - 40px)" aspect="product" eager /></ImageReveal><p className="mt-2 font-mono text-label text-ink-muted">REPRESENTATIVE RENEWABLE-ENERGY IMAGERY</p><EditorialText heading="Compliance infrastructure for renewable installation" primary><p>Renewably UK gives installers one place to manage protection, accreditation, records, and project evidence. Zentura joined on a long-term product engagement in June 2026.</p><p>The product needed to turn insurance, accreditation, customer records, and funded energy schemes into a clear, audit-ready workflow.</p></EditorialText><div className="mb-10 min-[720px]:hidden"><MetaTable rows={[{ label: "ROLE", value: "Product design · Engineering" }, { label: "SCOPE", value: "Strategy · Product · Systems" }, { label: "PROJECT", value: "Renewably UK · 2026" }]} /></div><div className="grid items-start gap-4 md:grid-cols-2"><ImageReveal><MediaFrame {...renewablyImages.wide} aspect="product" /></ImageReveal><ImageReveal><MediaFrame {...renewablyImages.portrait} aspect="device" /></ImageReveal></div><EditorialText heading="The working system"><p>We designed around the tasks installers repeat: company verification, TrustMark accreditation, Insurance Backed Guarantee issuance, CRM synchronisation, document management, and audit logging.</p><p>Product design and engineering stayed together so operational rules, interface decisions, and implementation constraints could be resolved in the same loop.</p></EditorialText><EditorialText heading="From policy to interface"><p>Compliance products carry obligations that cannot be reduced to a single happy path. Each status, permission, document, and exception needs a clear place in the system so installers can understand what is complete and what still requires attention.</p><p>The interface acts as an operational record as much as a set of screens. Product decisions are evaluated against the evidence a future audit may need, not only the speed of the immediate task.</p></EditorialText><div className="py-10"><MetaTable rows={[{ label: "ENGAGEMENT", value: "Long-term product partnership" }, { label: "STARTED", value: "09 June 2026" }, { label: "DISCIPLINES", value: "Product design · Engineering" }]} /></div><Link href="/work" className="inline-block font-mono text-label uppercase text-ink underline underline-offset-3">Back to Work</Link></article>; }
export default function Page(props: any) {
  return <Study {...props} />;
}
